name: vct
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
    - accelerate==0.15.0
    - tqdm==4.64.1
    - diffusers==0.10.1
    - opencv-python==4.7.0.72
    - IPython==8.9.0
    - transformers==4.26.1
    - datasets==2.10.1
    - numpy==1.22.1
    - scipy==1.7
    - requests==2.29.0
    - protobuf==3.20.0
    - attrs==20.1.0
! pip install torch==1.13.1+cu116 torchvision==0.14.1+cu116 torchaudio==0.13.1 --extra-index-url https://download.pytorch.org/whl/cu116